### ISSUE TITLE
Get schools retruns failed to get the course

### ISSUE THREAD

**Issue by HenryBrown0** [KentCompSoc/KentFlixServer#1]
To recreate: [https://kentflix-7f510.firebaseapp.com/api/v1/schools](https://kentflix-7f510.firebaseapp.com/api/v1/schools)

Returns: {"error":true,"infoMessage":"Failed to get the course"}

Theres currently no schools but should return failed to get schools

**Comment by LordHaywood** [comment]
Fixed issue and now API endpoint is now available and documentation is the same as before.
