### ISSUE TITLE
404 error on creating new school

### ISSUE THREAD

**Issue by HenryBrown0** [KentCompSoc/KentFlixServer#3]
Creating a new school returns a 404 error in the app. When copying and pasting URL into browser no issues. Maybe a cors issue?

To recreate:
1. Clone client side
2. Install
3. Go to [localhost:3000/new-school/](http://localhost:3000/new-school/)
4. Submit a new school

**Comment by HenryBrown0** [comment]
New school method is GET not POST

**Comment by LordHaywood** [comment]
Fixed and added to added to Master repository
