### ISSUE TITLE
Confusion between courses and moduels

### ISSUE THREAD

**Issue by HenryBrown0** [KentCompSoc/KentFlixServer#6]
Should a course be called a module, eg CO510 is a module inside the course Computer Science?

**Comment by HenryBrown0** [comment]
@HaywoodSolutions Thoughts?

**Comment by LordHaywood** [comment]
All crons dumped into courses but modules is currently being change to dump into modules instead. Working on ATM @HenryBrown0

**Comment by HenryBrown0** [comment]
Agreed that CO510 is a module and not a course? @HaywoodSolutions

**Comment by LordHaywood** [comment]
Yep, G400 is courses and CO520 is modules
